### ISSUE TITLE
Feature request: German localization

### ISSUE THREAD

**Issue by R3voA3** [Leopard20/Advanced-Developer-Tools-Localization#1]

**Comment by Leopard20** [comment]
Hi
I added some new stuff to the mod. 
I'll wait for you to finish this , then I'll upload the new localization file. It only adds 5~6 new stuff
Or if you want, you can make a pull request with your current changes, and I'll upload the new localization file with your changes applied, and you can continue after that.

**Comment by R3voA3** [comment]
Done
